/**
 * Beispieldaten für Entwicklung ohne Datenbankverbindung.
 * Fiktive Veranstaltungen in der Region Hohenlohekreis / Main-Tauber / Schwäbisch Hall.
 *
 * Viele Locations haben Events von mehreren Quellen → zeigt die Donut-Verteilung.
 */

import type { Event, Source } from "@/src/types/event";

export const MOCK_SOURCES: Source[] = [
  { id: 1, name: "Stadtradio Schwäbisch Hall" },
  { id: 2, name: "Hohenlohe-Ungefiltert" },
  { id: 3, name: "Main-Tauber-Kreis Veranstaltungen" },
  { id: 4, name: "Kulturamt Crailsheim" },
];

export const MOCK_EVENTS: Event[] = [

  // ── Schwäbisch Hall – Marktplatz (alle 4 Quellen) ────────────────────────
  {
    id: 1,
    title: "Stadtfest Schwäbisch Hall",
    event_date: "2026-03-15",
    event_time: "11:00:00",
    event_end_date: "2026-03-15",
    event_end_time: "22:00:00",
    url: null,
    raw_location: "Marktplatz, Schwäbisch Hall",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Marktplatz Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1123,
    longitude: 9.7301,
    description: "Großes Stadtfest mit Live-Musik, regionalen Spezialitäten und buntem Kunsthandwerk.",
    image_url: "https://picsum.photos/seed/ev1/280/140",
  },
  {
    id: 26,
    title: "Wochenmarkt Schwäbisch Hall",
    event_date: "2026-03-22",
    event_time: "08:00:00",
    event_end_date: "2026-03-22",
    event_end_time: "13:00:00",
    url: null,
    raw_location: "Marktplatz, Schwäbisch Hall",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Marktplatz Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1123,
    longitude: 9.7301,
    description: "Frischer Wochenmarkt mit Bauern aus der Region – Gemüse, Käse und selbst gebackenes Brot.",
    image_url: "https://picsum.photos/seed/ev26/280/140",
  },
  {
    id: 27,
    title: "Open-Air Konzert am Markt",
    event_date: "2026-04-18",
    event_time: "18:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Marktplatz, Schwäbisch Hall",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Marktplatz Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1123,
    longitude: 9.7301,
    description: "Sommerliches Konzert unter freiem Himmel mit Bands aus der ganzen Region.",
    image_url: "https://picsum.photos/seed/ev27/280/140",
  },
  {
    id: 28,
    title: "Kunstausstellung am Marktplatz",
    event_date: "2026-05-02",
    event_time: "10:00:00",
    event_end_date: "2026-05-04",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Marktplatz, Schwäbisch Hall",
    source_name: "Kulturamt Crailsheim",
    display_name: "Marktplatz Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1123,
    longitude: 9.7301,
    description: "Lokale Künstler präsentieren Malerei, Skulpturen und Fotografien unter freiem Himmel.",
    image_url: "https://picsum.photos/seed/ev28/280/140",
  },

  // ── Schwäbisch Hall – Rathaushof (3 Quellen) ─────────────────────────────
  {
    id: 2,
    title: "Jazz im Rathaushof",
    event_date: "2026-03-21",
    event_time: "20:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Rathaushof Schwäbisch Hall",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Rathaushof Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1130,
    longitude: 9.7315,
    description: "Stimmungsvoller Jazzabend im historischen Rathaushof – Eintritt frei.",
    image_url: "https://picsum.photos/seed/ev2/280/140",
  },
  {
    id: 29,
    title: "Kabarettabend im Rathaushof",
    event_date: "2026-04-11",
    event_time: "20:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Rathaushof Schwäbisch Hall",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Rathaushof Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1130,
    longitude: 9.7315,
    description: "Scharfzüngiges Kabarett mit regionalem Humor und politischer Satire.",
    image_url: "https://picsum.photos/seed/ev29/280/140",
  },
  {
    id: 30,
    title: "Autorenlesung & Gespräch",
    event_date: "2026-05-06",
    event_time: "19:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Rathaushof Schwäbisch Hall",
    source_name: "Kulturamt Crailsheim",
    display_name: "Rathaushof Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1130,
    longitude: 9.7315,
    description: "Bekannte Autorin liest aus ihrem neuen Roman – mit anschließender offener Fragerunde.",
    image_url: "https://picsum.photos/seed/ev30/280/140",
  },

  // ── Schwäbisch Hall – Haalplatz (2 Quellen) ──────────────────────────────
  {
    id: 3,
    title: "Frühlingsmarkt am Haalplatz",
    event_date: "2026-04-05",
    event_time: "09:00:00",
    event_end_date: "2026-04-06",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Haalplatz, Schwäbisch Hall",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Haalplatz Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1118,
    longitude: 9.7290,
    description: "Frühlingsstimmung am Haalplatz mit Pflanzen, Deko und regionalen Produkten.",
    image_url: "https://picsum.photos/seed/ev3/280/140",
  },
  {
    id: 31,
    title: "Kräuter- und Gartenmarkt",
    event_date: "2026-05-16",
    event_time: "09:00:00",
    event_end_date: "2026-05-17",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Haalplatz, Schwäbisch Hall",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Haalplatz Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1118,
    longitude: 9.7290,
    description: "Kräuterexperten und Gartenliebhaber präsentieren seltene Pflanzen und Heilkräuter.",
    image_url: "https://picsum.photos/seed/ev31/280/140",
  },

  // ── Schwäbisch Hall – Freilichtbühne ─────────────────────────────────────
  {
    id: 4,
    title: "Theater der Freilichtspiele",
    event_date: "2026-06-12",
    event_time: "20:30:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Freilichtbühne Schwäbisch Hall",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Freilichtbühne Schwäbisch Hall",
    city: "Schwäbisch Hall",
    latitude: 49.1135,
    longitude: 9.7325,
    description: "Spektakuläre Open-Air-Inszenierung im malerischen Kulissenschuppen der Freilichtspiele.",
    image_url: "https://picsum.photos/seed/ev4/280/140",
  },

  // ── Schwäbisch Hall – Hospitalkirche ─────────────────────────────────────
  {
    id: 5,
    title: "Konzert in der Hospitalkirche",
    event_date: "2026-05-03",
    event_time: "18:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Hospitalkirche, Schwäbisch Hall",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: null,
    city: "Schwäbisch Hall",
    latitude: 49.1110,
    longitude: 9.7308,
    description: "Kammerkonzert in der gotischen Hospitalkirche – Werke von Bach und Händel.",
    image_url: "https://picsum.photos/seed/ev5/280/140",
  },

  // ── Burg Langenburg (3 Quellen) ───────────────────────────────────────────
  {
    id: 6,
    title: "Burgfest Langenburg",
    event_date: "2026-05-01",
    event_time: "10:00:00",
    event_end_date: "2026-05-03",
    event_end_time: "18:00:00",
    url: null,
    raw_location: "Burg Langenburg",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Burg Langenburg",
    city: "Langenburg",
    latitude: 49.2478,
    longitude: 9.8607,
    description: "Mittelalterliches Burgfest mit Gauklern, Rittern und historischen Handwerkern.",
    image_url: "https://picsum.photos/seed/ev6/280/140",
  },
  {
    id: 35,
    title: "Ritterturnier auf Burg Langenburg",
    event_date: "2026-05-02",
    event_time: "14:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Burg Langenburg",
    source_name: "Kulturamt Crailsheim",
    display_name: "Burg Langenburg",
    city: "Langenburg",
    latitude: 49.2478,
    longitude: 9.8607,
    description: "Historisches Ritterturnier mit authentischer Kampfshow und Kostümführungen.",
    image_url: "https://picsum.photos/seed/ev35/280/140",
  },
  {
    id: 36,
    title: "Konzert auf der Burg",
    event_date: "2026-06-14",
    event_time: "19:30:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Burg Langenburg",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Burg Langenburg",
    city: "Langenburg",
    latitude: 49.2478,
    longitude: 9.8607,
    description: "Romantisches Konzert auf der Burgterrasse mit Blick ins Jagsttal.",
    image_url: "https://picsum.photos/seed/ev36/280/140",
  },

  // ── Künzelsau – Marktplatz (alle 4 Quellen) ───────────────────────────────
  {
    id: 7,
    title: "Weinfest Künzelsau",
    event_date: "2026-04-25",
    event_time: "14:00:00",
    event_end_date: "2026-04-26",
    event_end_time: "22:00:00",
    url: null,
    raw_location: "Innenstadt Künzelsau",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Marktplatz Künzelsau",
    city: "Künzelsau",
    latitude: 49.2779,
    longitude: 9.6785,
    description: "Weinfest mit Winzern aus der Hohenloher Region – Verkostung und Kellerführungen.",
    image_url: "https://picsum.photos/seed/ev7/280/140",
  },
  {
    id: 37,
    title: "Stadtlauf Künzelsau",
    event_date: "2026-04-26",
    event_time: "10:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Innenstadt Künzelsau",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Marktplatz Künzelsau",
    city: "Künzelsau",
    latitude: 49.2779,
    longitude: 9.6785,
    description: "Volkslauf durch die Innenstadt – Strecken für Jedermann von 5 bis 21 km.",
    image_url: "https://picsum.photos/seed/ev37/280/140",
  },
  {
    id: 38,
    title: "Kunsthandwerkermarkt Künzelsau",
    event_date: "2026-05-24",
    event_time: "10:00:00",
    event_end_date: "2026-05-25",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Marktplatz Künzelsau",
    source_name: "Kulturamt Crailsheim",
    display_name: "Marktplatz Künzelsau",
    city: "Künzelsau",
    latitude: 49.2779,
    longitude: 9.6785,
    description: "Über 50 Aussteller zeigen einzigartiges Kunsthandwerk – von Keramik bis Schmuck.",
    image_url: "https://picsum.photos/seed/ev38/280/140",
  },
  {
    id: 39,
    title: "Open-Air Kino Künzelsau",
    event_date: "2026-06-20",
    event_time: "21:30:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Marktplatz Künzelsau",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Marktplatz Künzelsau",
    city: "Künzelsau",
    latitude: 49.2779,
    longitude: 9.6785,
    description: "Sommerliches Freiluftkino unter Sternen – Blockbuster und Indie-Filme.",
    image_url: "https://picsum.photos/seed/ev39/280/140",
  },

  // ── Öhringen – Stadtpark (3 Quellen) ─────────────────────────────────────
  {
    id: 8,
    title: "Open-Air Konzert Öhringen",
    event_date: "2026-06-20",
    event_time: "19:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Stadtpark Öhringen",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Stadtpark Öhringen",
    city: "Öhringen",
    latitude: 49.2009,
    longitude: 9.5049,
    description: "Sommerkonzert im grünen Stadtpark – Bring-your-own-blanket und entspannen.",
    image_url: "https://picsum.photos/seed/ev8/280/140",
  },
  {
    id: 44,
    title: "Familienfest im Stadtpark",
    event_date: "2026-05-31",
    event_time: "11:00:00",
    event_end_date: "2026-05-31",
    event_end_time: "18:00:00",
    url: null,
    raw_location: "Stadtpark Öhringen",
    source_name: "Kulturamt Crailsheim",
    display_name: "Stadtpark Öhringen",
    city: "Öhringen",
    latitude: 49.2009,
    longitude: 9.5049,
    description: "Buntes Familienfest mit Spielen, Hüpfburg, Ponyreiten und Kinderschminken.",
    image_url: "https://picsum.photos/seed/ev44/280/140",
  },
  {
    id: 45,
    title: "Freiluftkino Öhringen",
    event_date: "2026-06-27",
    event_time: "21:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Stadtpark Öhringen",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Stadtpark Öhringen",
    city: "Öhringen",
    latitude: 49.2009,
    longitude: 9.5049,
    description: "Kino unter dem Sternenhimmel – Filmgenuss mit Popcorn im Freien.",
    image_url: "https://picsum.photos/seed/ev45/280/140",
  },

  // ── Gerabronn ─────────────────────────────────────────────────────────────
  {
    id: 9,
    title: "Brauereifest Gerabronn",
    event_date: "2026-04-18",
    event_time: "15:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Brauereigelände Gerabronn",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: null,
    city: "Gerabronn",
    latitude: 49.2566,
    longitude: 9.9125,
    description: "Fest auf dem Brauereigelände mit frischem Bier vom Fass und Live-Musik.",
    image_url: "https://picsum.photos/seed/ev9/280/140",
  },

  // ── Neuenstein ────────────────────────────────────────────────────────────
  {
    id: 10,
    title: "Kunsthandwerkermarkt Neuenstein",
    event_date: "2026-05-17",
    event_time: "10:00:00",
    event_end_date: "2026-05-18",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Schlosspark Neuenstein",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Schloss Neuenstein",
    city: "Neuenstein",
    latitude: 49.2088,
    longitude: 9.7139,
    description: "Kunsthandwerker und Designer präsentieren ihre Arbeiten im Barockgarten.",
    image_url: "https://picsum.photos/seed/ev10/280/140",
  },

  // ── Kupferzell ────────────────────────────────────────────────────────────
  {
    id: 11,
    title: "Sporttag Kupferzell",
    event_date: "2026-05-10",
    event_time: "09:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Sportplatz Kupferzell",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: null,
    city: "Kupferzell",
    latitude: 49.2310,
    longitude: 9.7007,
    description: "Sportfest für die ganze Familie mit Turnieren, Vorführungen und Vereinspräsentationen.",
    image_url: "https://picsum.photos/seed/ev11/280/140",
  },

  // ── Kirchberg an der Jagst ────────────────────────────────────────────────
  {
    id: 12,
    title: "Heimatfest Kirchberg an der Jagst",
    event_date: "2026-05-30",
    event_time: "11:00:00",
    event_end_date: "2026-06-01",
    event_end_time: "20:00:00",
    url: null,
    raw_location: "Marktplatz Kirchberg",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Marktplatz Kirchberg a.d. Jagst",
    city: "Kirchberg an der Jagst",
    latitude: 49.2001,
    longitude: 9.9530,
    description: "Dreitägiges Heimatfest mit historischem Umzug, Festzelt und Kinderprogramm.",
    image_url: "https://picsum.photos/seed/ev12/280/140",
  },

  // ── Rothenburg ob der Tauber ──────────────────────────────────────────────
  {
    id: 13,
    title: "Mittelaltermarkt Rothenburg ob der Tauber",
    event_date: "2026-04-03",
    event_time: "10:00:00",
    event_end_date: "2026-04-06",
    event_end_time: "19:00:00",
    url: null,
    raw_location: "Altstadt Rothenburg",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Marktplatz Rothenburg ob der Tauber",
    city: "Rothenburg ob der Tauber",
    latitude: 49.3778,
    longitude: 10.1789,
    description: "Mittelaltermarkt in der weltberühmten Altstadt – Händler, Gaukler und Musikanten.",
    image_url: "https://picsum.photos/seed/ev13/280/140",
  },

  // ── Weikersheim – Marktplatz (3 Quellen) ─────────────────────────────────
  {
    id: 14,
    title: "Stadtlauf Weikersheim",
    event_date: "2026-05-24",
    event_time: "09:30:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Marktplatz Weikersheim",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Marktplatz Weikersheim",
    city: "Weikersheim",
    latitude: 49.4780,
    longitude: 9.8984,
    description: "Volkslauf durch die historische Residenzstadt – Strecken für alle Altersgruppen.",
    image_url: "https://picsum.photos/seed/ev14/280/140",
  },
  {
    id: 40,
    title: "Frühlingskonzert im Schlosspark",
    event_date: "2026-05-03",
    event_time: "15:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Schlosspark Weikersheim",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Marktplatz Weikersheim",
    city: "Weikersheim",
    latitude: 49.4780,
    longitude: 9.8984,
    description: "Frühlingshaftes Konzert im barocken Schlosspark – Bläser und Streicher.",
    image_url: "https://picsum.photos/seed/ev40/280/140",
  },
  {
    id: 41,
    title: "Weinmarkt Weikersheim",
    event_date: "2026-06-07",
    event_time: "11:00:00",
    event_end_date: "2026-06-08",
    event_end_time: "20:00:00",
    url: null,
    raw_location: "Marktplatz Weikersheim",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Marktplatz Weikersheim",
    city: "Weikersheim",
    latitude: 49.4780,
    longitude: 9.8984,
    description: "Tauber-Weinmarkt mit Winzern aus dem Lieblichen Taubertal – Rosé, Rot, Weiß.",
    image_url: "https://picsum.photos/seed/ev41/280/140",
  },

  // ── Schloss Weikersheim ───────────────────────────────────────────────────
  {
    id: 15,
    title: "Konzert im Schloss Weikersheim",
    event_date: "2026-06-07",
    event_time: "20:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Schloss Weikersheim",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Schloss Weikersheim",
    city: "Weikersheim",
    latitude: 49.4771,
    longitude: 9.8971,
    description: "Festliches Konzert im Renaissanceschloss – Abendatmosphäre im historischen Gewölbe.",
    image_url: "https://picsum.photos/seed/ev15/280/140",
  },

  // ── Bad Mergentheim (3 Quellen) ───────────────────────────────────────────
  {
    id: 16,
    title: "Kunstausstellung Bad Mergentheim",
    event_date: "2026-04-10",
    event_time: "14:00:00",
    event_end_date: "2026-05-10",
    event_end_time: null,
    url: null,
    raw_location: "Schloss Bad Mergentheim",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Deutschordensschloss Bad Mergentheim",
    city: "Bad Mergentheim",
    latitude: 49.4943,
    longitude: 9.7710,
    description: "Monatslange Ausstellung zeitgenössischer Kunst im Deutschordensschloss.",
    image_url: "https://picsum.photos/seed/ev16/280/140",
  },
  {
    id: 42,
    title: "Kurkonzert im Kurpark",
    event_date: "2026-05-17",
    event_time: "15:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Kurpark Bad Mergentheim",
    source_name: "Kulturamt Crailsheim",
    display_name: "Deutschordensschloss Bad Mergentheim",
    city: "Bad Mergentheim",
    latitude: 49.4943,
    longitude: 9.7710,
    description: "Entspanntes Kurkonzert im Kurpark mit Kurkapelle und Kurorchester.",
    image_url: "https://picsum.photos/seed/ev42/280/140",
  },
  {
    id: 43,
    title: "Stadtfest Bad Mergentheim",
    event_date: "2026-06-13",
    event_time: "11:00:00",
    event_end_date: "2026-06-14",
    event_end_time: "22:00:00",
    url: null,
    raw_location: "Innenstadt Bad Mergentheim",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Deutschordensschloss Bad Mergentheim",
    city: "Bad Mergentheim",
    latitude: 49.4943,
    longitude: 9.7710,
    description: "Zweitägiges Stadtfest mit Bühnenauftritten, Händlern und Gastronomie.",
    image_url: "https://picsum.photos/seed/ev43/280/140",
  },

  // ── Weinwanderung Taubertal ───────────────────────────────────────────────
  {
    id: 17,
    title: "Weinwanderung Taubertal",
    event_date: "2026-06-06",
    event_time: "10:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Taubertal bei Bad Mergentheim",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: null,
    city: "Bad Mergentheim",
    latitude: 49.4100,
    longitude: 9.9500,
    description: "Geführte Weinwanderung durch die Weinberge entlang der Tauber – 12 km.",
    image_url: "https://picsum.photos/seed/ev17/280/140",
  },

  // ── Boxberg ───────────────────────────────────────────────────────────────
  {
    id: 18,
    title: "Konzert Boxberg",
    event_date: "2026-05-22",
    event_time: "20:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Kulturhalle Boxberg",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: null,
    city: "Boxberg",
    latitude: 49.4870,
    longitude: 9.6426,
    description: "Konzertabend in der Kulturhalle – Klassik trifft Jazz.",
    image_url: "https://picsum.photos/seed/ev18/280/140",
  },

  // ── Blaufelden ────────────────────────────────────────────────────────────
  {
    id: 19,
    title: "Nachtmarkt Blaufelden",
    event_date: "2026-05-16",
    event_time: "18:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Ortsmitte Blaufelden",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: null,
    city: "Blaufelden",
    latitude: 49.3018,
    longitude: 10.0205,
    description: "Abendlicher Nachtmarkt mit Lichtinstallationen, Straßenkünstlern und Kulinarik.",
    image_url: "https://picsum.photos/seed/ev19/280/140",
  },

  // ── Crailsheim – Marktplatz (alle 4 Quellen) ──────────────────────────────
  {
    id: 20,
    title: "Flohmarkt Crailsheim",
    event_date: "2026-04-12",
    event_time: "08:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Innenstadt Crailsheim",
    source_name: "Kulturamt Crailsheim",
    display_name: "Marktplatz Crailsheim",
    city: "Crailsheim",
    latitude: 49.1350,
    longitude: 10.0666,
    description: "Großer Flohmarkt mit über 200 Ständen – Raritäten, Antiquitäten und Alltagsdinge.",
    image_url: "https://picsum.photos/seed/ev20/280/140",
  },
  {
    id: 32,
    title: "Bauernmarkt Crailsheim",
    event_date: "2026-04-25",
    event_time: "08:00:00",
    event_end_date: "2026-04-25",
    event_end_time: "13:00:00",
    url: null,
    raw_location: "Marktplatz Crailsheim",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Marktplatz Crailsheim",
    city: "Crailsheim",
    latitude: 49.1350,
    longitude: 10.0666,
    description: "Regionaler Bauernmarkt mit frischem Gemüse, Fleisch und Milchprodukten direkt vom Hof.",
    image_url: "https://picsum.photos/seed/ev32/280/140",
  },
  {
    id: 33,
    title: "Stadtkonzert Crailsheim",
    event_date: "2026-05-09",
    event_time: "19:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Marktplatz Crailsheim",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Marktplatz Crailsheim",
    city: "Crailsheim",
    latitude: 49.1350,
    longitude: 10.0666,
    description: "Großes Stadtkonzert mit lokalen Bands und Orchestern – Eintritt frei.",
    image_url: "https://picsum.photos/seed/ev33/280/140",
  },
  {
    id: 34,
    title: "Kunsthandwerkermarkt Crailsheim",
    event_date: "2026-06-07",
    event_time: "10:00:00",
    event_end_date: "2026-06-08",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Marktplatz Crailsheim",
    source_name: "Main-Tauber-Kreis Veranstaltungen",
    display_name: "Marktplatz Crailsheim",
    city: "Crailsheim",
    latitude: 49.1350,
    longitude: 10.0666,
    description: "Kunsthandwerker aus der Region präsentieren Keramik, Holzarbeiten und Textilien.",
    image_url: "https://picsum.photos/seed/ev34/280/140",
  },

  // ── Crailsheim – Fußgängerzone ────────────────────────────────────────────
  {
    id: 21,
    title: "Nachtmarkt Crailsheim",
    event_date: "2026-06-13",
    event_time: "17:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Fußgängerzone Crailsheim",
    source_name: "Kulturamt Crailsheim",
    display_name: "Fußgängerzone Crailsheim",
    city: "Crailsheim",
    latitude: 49.1340,
    longitude: 10.0655,
    description: "Abendmarkt in der beleuchteten Fußgängerzone – Shopping, Streetfood und Livemusik.",
    image_url: "https://picsum.photos/seed/ev21/280/140",
  },

  // ── Crailsheim – Kulturbahnhof ────────────────────────────────────────────
  {
    id: 22,
    title: "Rockkonzert Kulturbahnhof",
    event_date: "2026-03-28",
    event_time: "21:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Kulturbahnhof Crailsheim",
    source_name: "Kulturamt Crailsheim",
    display_name: null,
    city: "Crailsheim",
    latitude: 49.1333,
    longitude: 10.0700,
    description: "Rockige Nacht im Kulturbahnhof – drei Bands, Lichtshow und Late-Night-Bar.",
    image_url: "https://picsum.photos/seed/ev22/280/140",
  },

  // ── Crailsheim – Stadtpark ────────────────────────────────────────────────
  {
    id: 23,
    title: "Kinderfest im Stadtpark",
    event_date: "2026-06-14",
    event_time: "13:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Stadtpark Crailsheim",
    source_name: "Kulturamt Crailsheim",
    display_name: "Stadtpark Crailsheim",
    city: "Crailsheim",
    latitude: 49.1360,
    longitude: 10.0640,
    description: "Buntes Kinderfest mit Puppenspielen, Bastelständen und Zirkusvorführungen.",
    image_url: "https://picsum.photos/seed/ev23/280/140",
  },

  // ── Gaildorf – Marktplatz (3 Quellen) ────────────────────────────────────
  {
    id: 24,
    title: "Musiknacht Gaildorf",
    event_date: "2026-04-19",
    event_time: "20:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Marktplatz Gaildorf",
    source_name: "Kulturamt Crailsheim",
    display_name: "Marktplatz Gaildorf",
    city: "Gaildorf",
    latitude: 49.0067,
    longitude: 9.7706,
    description: "Große Musiknacht mit Auftritten verschiedener Genres – von Folk bis Elektronik.",
    image_url: "https://picsum.photos/seed/ev24/280/140",
  },
  {
    id: 46,
    title: "Frühlingsmarkt Gaildorf",
    event_date: "2026-04-05",
    event_time: "09:00:00",
    event_end_date: "2026-04-06",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Marktplatz Gaildorf",
    source_name: "Stadtradio Schwäbisch Hall",
    display_name: "Marktplatz Gaildorf",
    city: "Gaildorf",
    latitude: 49.0067,
    longitude: 9.7706,
    description: "Frühlingserwachen am Marktplatz – Pflanzen, Kräuter, Deko und regionale Küche.",
    image_url: "https://picsum.photos/seed/ev46/280/140",
  },
  {
    id: 47,
    title: "Handwerkermarkt Gaildorf",
    event_date: "2026-05-30",
    event_time: "10:00:00",
    event_end_date: "2026-05-31",
    event_end_time: "17:00:00",
    url: null,
    raw_location: "Marktplatz Gaildorf",
    source_name: "Hohenlohe-Ungefiltert",
    display_name: "Marktplatz Gaildorf",
    city: "Gaildorf",
    latitude: 49.0067,
    longitude: 9.7706,
    description: "Handwerker aus dem Limpurger Land zeigen alte Handwerkskünste und bieten Waren an.",
    image_url: "https://picsum.photos/seed/ev47/280/140",
  },

  // ── Crailsheim – Treffpunkt Rathaus (Fahrradtour) ─────────────────────────
  {
    id: 25,
    title: "Fahrradtour durch das Jagsttal",
    event_date: "2026-05-09",
    event_time: "09:00:00",
    event_end_date: null,
    event_end_time: null,
    url: null,
    raw_location: "Treffpunkt Rathaus Crailsheim",
    source_name: "Kulturamt Crailsheim",
    display_name: null,
    city: "Crailsheim",
    latitude: 49.1350,
    longitude: 10.0666,
    description: "Geführte Fahrradtour entlang der Jagst – 40 km durch malerische Auenlandschaft.",
    image_url: "https://picsum.photos/seed/ev25/280/140",
  },
];
